### PR TITLE
[FEATURE] Add composer.json merge script

### PR DESCRIPTION
**Pull request by kitsunet**
Adds the Script to merge composer.json configuration from
multiple packages for a joined repository, aka development
collection.

Releases: master, 3.0, 2.3

### CODE REVIEW

**Comment by kitsunet** [comment]
@kdambekalns and this is the merge script.
template file will be added to the collections in following pull requests.

The script needs to be called in the collection repository directory and as argument you need to give the version for the replaced packages (dev-master, 2.0.x-dev etc.)

**Comment by kdambekalns** [comment]
Small nitpick: I'd like the name `ComposerManifestMerger` a lot better, since that is what it does.

**Comment by kitsunet** [comment]
Sure, lets do that. It began it's life as simple merger.php ;)

**Comment by kitsunet** [comment]
And updated.

**Comment by kdambekalns** [comment]
A remark on the replaced version - that could be `self.version`, to always replace "itself", see https://getcomposer.org/doc/04-schema.md#replace - no?

**Comment by kitsunet** [comment]
Nice, didn't know about that. Will adapt

**Comment by kitsunet** [comment]
And adapted to use self version.

**Comment by kdambekalns** [comment]
:+1: by reading

**Comment by robertlemke** [comment]
Just trying out the script and I'm wondering if the resulting composer.json is really correct:

```javascript
{
    "name": "neos/neos-development-collection",
    "description": "Neos packages in a joined repository for pull requests.",
    "type": "neos-package-collection",
    "require": {
        "typo3/flow": [
            "*",
            "*",
            "*",
            "*"
        ],
        "typo3/imagine": "*",
        "php": ">=5.4.0",
        "typo3/kickstart": "*",
…
```

I'm referring to the "typo3/flow" dependencies: I guess the resulting array is a bug?

**Comment by kitsunet** [comment]
Correct, this was a mistake. I updated the script and the generated JSON for Neos looks like this now:

```
{
    "name": "neos/neos-development-collection",
    "description": "Neos packages in a joined repository for pull requests.",
    "type": "neos-package-collection",
    "require": {
        "typo3/flow": "*",
        "typo3/imagine": "*",
        "php": ">=5.4.0",
        "typo3/kickstart": "*",
        "typo3/party": "*",
        "typo3/setup": "*",
        "typo3/twitter-bootstrap": "*",
        "typo3/eel": "*",
        "gedmo/doctrine-extensions": "2.3.*"
    },
    "replace": {
        "typo3/media": "self.version",
        "typo3/neos-kickstarter": "self.version",
        "typo3/neos-nodetypes": "self.version",
        "typo3/neos": "self.version",
        "typo3/typo3cr": "self.version",
        "typo3/typoscript": "self.version"
    },
    "suggest": {
        "typo3/neos-kickstarter": "Helps with creating new site packages for Neos."
    },
    "autoload": {
        "psr-0": {
            "TYPO3\\Media": "TYPO3.Media/Classes",
            "TYPO3\\Neos\\Kickstarter": "TYPO3.Neos.Kickstarter/Classes",
            "TYPO3\\Neos\\NodeTypes": "TYPO3.Neos.NodeTypes/Classes",
            "TYPO3\\Neos": "TYPO3.Neos/Classes",
            "TYPO3\\TYPO3CR": "TYPO3.TYPO3CR/Classes",
            "TYPO3\\TypoScript": "TYPO3.TypoScript/Classes"
        }
    },
    "extra": {
        "installer-name": "Neos",
        "neos": {
            "warning": "AUTOGENERATED FILE, ONLY MODIFY THE .composer.json IN THIS DIRECTORY AND RUN THE MERGE SCRIPT.",
            "installer-resource-folders": [
                "TYPO3.Neos/Resources/Private/Installer/"
            ]
        },
        "typo3/flow": {
            "manage-resources": true
        }
    }
}
```

**Comment by robertlemke** [comment]
:+1: looks good to me, I also tried the script locally. Let's merge it.

**Comment by kdambekalns** [comment]
:+1:

**Pull request merged**
