### PR TITLE
TASK: Add ComposerManifestUpdater that can be used with TravisCI

### PR DESCRIPTION
**Pull request by johannessteu**

### CODE REVIEW

**Comment by kitsunet** [comment]
First and biggest step to make travis finally understand autoload changes in PRs as with this the PR can be correctly fetched via composer :)

**Comment by johannessteu** [comment]
Yeah! So here are some infos for this change: 

Right now in travis we clone the distri package, run composer install, rm the neos-dev-collection and move the one that travis will cloned by default (the pr code) to Packages/Neos. So changes to classes are not autolaoded because there is no more composer magic. Instead use some custom class loading in our test bootstrap.

This change adds a script that modifies the composer.json. It will add the PR repo as a repository and require the PR branch as an alias for the default version. So after this script is applied we can run composer update again and use the correct autoload changes.

This came  up when we moved from PSR-0 to PSR-4 because our custom class loader only respects PSR-0.

So after this one is merged i'll take care of the adjustments in our .travis.yaml

Here is my test-pr: https://travis-ci.org/johannessteu/neos-development-collection/jobs/169022984
This PR is a change from PSR-0 to PSR-4. The setup also requieres some custom branches for the distri so my BuildEssential package is loaded. We need to adjust travis like this:
https://github.com/johannessteu/neos-development-collection/commit/9f94bbb60edeb43a9efc984c33f3a4a8e367e67c
Just one addition to this: on line 38 we will use the env var `NEOS_TARGET_VERSION `

Here is the PR for the exact same change but with our custom setup:
https://github.com/neos/neos-development-collection/pull/1186
PR with this script:
https://github.com/johannessteu/neos-development-collection/pull/1062

**Comment by kitsunet** [comment]
I am still convinced that if we load the composer autoloader we don't need our own

**Comment by johannessteu** [comment]
Yeah, just wanted to test something. The test does not work atm. When i talked to you it was green, now it's red. Dunno why. Tested this morning to deactivate the autoloader, but that does not help at all >.>

**Pull request merged**
